name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  workflow-run-id:
    type: string
    description: The workflow run ID to start the search for workflows from. Defaults to the current workflow run.
    required: false
    default: ${{ github.run_id }}
  access-token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: ${{ github.token }}
    required: false
  tag:
    type: string
    required: true
    descroption: 'tag the PRs with this tag'
    default: 'deployed'
runs:
  using: 'node16'
  main: 'dist/index.js'
